### PR TITLE
Still adding images

### PR DESCRIPTION
**Pull request by windrockstar**

### CODE REVIEW

**Comment by revilowaldow** [comment]
So this was the issue I was hoping wouldn't occur.
I'm going to defer to @TheGiddyLimit on what he'd prefer to do but a significant proportion of the assets are duplication/bloat.
A large number of the files added are effectively directly lifted 5e Art, which is common for DMsGuild products.
For example the images below already exist on the site and could be internally referenced easily with
```json
"token": {
	"name": "Barlgura",
	"source": "MM"
}
```
```json
{
	"type": "image",
	"href": {
		"type": "internal",
		"path": "bestiary/MM/Barlgura.webp"
	}
}
```
image
image

**Comment by TheGiddyLimit** [comment]
definitely not ideal. Briefly tried some perceptual hashing vs. the current bestiary, with limited success:

```
Likely Existing file (distance = 0)! "img/DarkSunCreatureCatalog/Spider_Crystal_White_Widow_Avatar.webp" matched "bestiary/MM/Phase Spider.webp"
Likely Existing file (distance = 1)! "img/DarkSunCreatureCatalog/Gith_Savage_Avatar.webp" matched "bestiary/MM/Githyanki.webp"
Likely Existing file (distance = 0)! "img/DarkSunCreatureCatalog/Gith_Drone_Avatar.webp" matched "bestiary/MM/Githzerai.webp"
Likely Existing file (distance = 0)! "img/DarkSunCreatureCatalog/Giant_Giant_Shadow_v2_Avatar.webp" matched "bestiary/MM/Ogre Zombie.webp"
Likely Existing file (distance = 1)! "img/AngryGolemGamesMonsterManual3/Sword_Wraith_Commander_Avatar.webp" matched "bestiary/MPMM/Sword Wraith Warrior.webp"
Likely Existing file (distance = 2)! "img/AngryGolemGamesMonsterManual3/Stone_Defender_Avatar.webp" matched "bestiary/MTF/Stone Defender.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Stone_Cursed_Avatar.webp" matched "bestiary/MPMM/Stone Cursed.webp"
Likely Existing file (distance = 2)! "img/AngryGolemGamesMonsterManual3/Stirge_Avatar.webp" matched "bestiary/MM/Stirge.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Spider_Avatar.webp" matched "bestiary/MM/Spider.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Smoke_Mephit_Avatar.webp" matched "bestiary/MM/Smoke Mephit.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Shrieker_Avatar.webp" matched "bestiary/MM/Shrieker.webp"
Likely Existing file (distance = 3)! "img/AngryGolemGamesMonsterManual3/Shoosuva_Avatar.webp" matched "bestiary/MPMM/Shoosuva.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Shield_Guardian_Avatar.webp" matched "bestiary/MM/Shield Guardian.webp"
Likely Existing file (distance = 1)! "img/AngryGolemGamesMonsterManual3/Riding_Horse_Avatar.webp" matched "bestiary/MM/Riding Horse.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Red_Dragon_Young_Avatar.webp" matched "bestiary/MM/Red Dragon.webp"
Likely Existing file (distance = 2)! "img/AngryGolemGamesMonsterManual3/Red_Abishai_Avatar.webp" matched "bestiary/MPMM/Red Abishai.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Quickling_Avatar.webp" matched "bestiary/MPMM/Quickling.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Pixie_Avatar.webp" matched "bestiary/MM/Pixie.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Owl_Avatar.webp" matched "bestiary/MM/Giant Owl.webp"
Likely Existing file (distance = 1)! "img/AngryGolemGamesMonsterManual3/Ogre_Battering_Ram_Avatar.webp" matched "bestiary/MPMM/Ogre Battering Ram.webp"
Likely Existing file (distance = 1)! "img/AngryGolemGamesMonsterManual3/Oblex_Spawn_Avatar.webp" matched "bestiary/MPMM/Oblex Spawn.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Oaken_Bolter_Avatar.webp" matched "bestiary/MTF/Oaken Bolter.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual3/Nightmare_Avatar.webp" matched "bestiary/MM/Nightmare.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual2/Malison_Yuan_Ti_Type_1_Avatar.webp" matched "bestiary/MM/Yuan-ti Malison.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual2/Lion_Avatar.webp" matched "bestiary/MOT/Fleecemane Lion.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual2/Kuo_Toa_Archpriest_Avatar.webp" matched "bestiary/MM/Kuo-toa Archpriest.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual2/Korred_Avatar.webp" matched "bestiary/MPMM/Korred.webp"
Likely Existing file (distance = 1)! "img/AngryGolemGamesMonsterManual2/Ice_Devil_Gelugon_Avatar.webp" matched "bestiary/MM/Ice Devil.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual2/Hobgoblin_Devastator_Avatar.webp" matched "bestiary/VGM/Hobgoblin Devastator.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual2/Histachii_Yuan-Ti_Avatar.webp" matched "bestiary/MPMM/Yuan-ti Broodguard.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual2/Hezrou_Avatar.webp" matched "bestiary/MM/Death Slaad.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Griffon_Avatar.webp" matched "bestiary/MM/Griffon.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Grick_Alpha_Avatar.webp" matched "bestiary/MM/Grick.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Grell_Avatar.webp" matched "bestiary/MM/Grell.webp"
Likely Existing file (distance = 2)! "img/AngryGolemGamesMonsterManual/Green_Abishai_Avatar.webp" matched "bestiary/MPMM/Green Abishai.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Goat_Avatar.webp" matched "bestiary/IDRotF/Mountain Goat.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Gnoll_Hunter_Avatar.webp" matched "bestiary/MM/Gnoll.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Gas_Spore_Avatar.webp" matched "bestiary/MM/Gas Spore.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Frog_Avatar.webp" matched "bestiary/MM/Giant Frog.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Flesh_Golem_Avatar.webp" matched "bestiary/MM/Flesh Golem.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Dust_Mephit_Avatar.webp" matched "bestiary/MM/Dust Mephit.webp"
Likely Existing file (distance = 3)! "img/AngryGolemGamesMonsterManual/Duergar_Despot_Avatar.webp" matched "bestiary/MPMM/Duergar Hammerer.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Drider_Avatar.webp" matched "bestiary/MM/Drider.webp"
Likely Existing file (distance = 1)! "img/AngryGolemGamesMonsterManual/Cyclopskin_Avatar.webp" matched "bestiary/MM/Cyclops.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Copper_Dragon_Wyrmling_Avatar.webp" matched "bestiary/MM/Bronze Dragon Wyrmling.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Brass_Dragon_Wyrmling_Avatar.webp" matched "bestiary/MM/Bronze Dragon Wyrmling.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Boggle_Avatar.webp" matched "bestiary/MPMM/Boggle.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Black_Dragon_Wyrmling_Avatar.webp" matched "bestiary/MM/Black Dragon Wyrmling.webp"
Likely Existing file (distance = 1)! "img/AngryGolemGamesMonsterManual/Astral_dreadnought_Avatar.webp" matched "bestiary/MPMM/Astral Dreadnought.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Ash_Mephit_Avatar.webp" matched "bestiary/MM/Smoke Mephit.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Air_Elemental_Avatar.webp" matched "bestiary/MM/Air Elemental.webp"
Likely Existing file (distance = 0)! "img/AngryGolemGamesMonsterManual/Abomination_Yuan-Ti_Avatar.webp" matched "bestiary/MM/Yuan-ti Abomination.webp"
```

will have to tinker with it some more; it seems notably bad at tokens

---

Ideally, the solution would:

- be usefully accurate (no false positives; catch a meaningful percentage of real matches -- at least enough to fail a pipeline/trigger human review)
- be `node`-based, so people don't have to e.g. set up a Python env
- be fast enough to run as a test in repo `Actions`
- have the option to auto-fix image links it finds (with the sensitivity turned/optionally adjustable up to allow more false positives through but fix more bad links at the same time)

Perceptual hashing seems the closest we'll get; will have another crack at it when there's less Foundry stuff on my plate, and leave this PR open for now. If it seems like it's not worth fixing, then just have to deal with junk in the repo. Increasing the friction of adding images + soaking up lots of my own time building out a big solution to this are two things I want to avoid!

**Comment by windrockstar** [comment]
Sorry I didn't think I was creating all these problems.
Would you rather I close the pr and "split" it into a PR for each json source ?

**Comment by TheGiddyLimit** [comment]
If you've sources which you know don't contain any D&D Monster Manual images, then sure, go for it; they can be merged no problem

**Pull request closed without merging**
