### PR TITLE
Added images for Griffon's Saddlebag Year 4 items

### PR DESCRIPTION
**Pull request by unknown117343**

### CODE REVIEW

**Review by revilowaldow — CHANGES_REQUESTED** [review]
`TGSY4` is not present in the list of legacy homebrew sources and will be too short to be a valid source.
https://github.com/TheGiddyLimit/5etools-utils/blob/master/schema-template/sources-homebrew-legacy.json

Please ensure your folder matches a valid json source id.

**Comment by revilowaldow** [comment]
@TheGiddyLimit could we implement a check for valid folder names, easier than me pulling up the list each time?
 
Must pass either of:
- In legacy list
- Complies with brew pattern (with `:` taken out)

**Comment by TheGiddyLimit** [comment]
not so much;

- checking vs. the legacy list is easy
- checking against the brew pattern is not; one could have a source which is just `a:::::` and it'd be valid, but the dir `a` here wouldn't pass muster. Since there's no "list of all brew sources" to check against (and we assume images are made here _before_ the source gets made in the main homebrew repo) there's no lookup, and therefore no way to do dirname -> source

the intent was that testing would be done on the `homebrew` repo side of things tbf

the hatchet route would be to make the pattern e.g. `^[-a-zA-Z0-9]+$` and avoid the problem entirely, which might be a sensible thing to enforce going forwards

**Comment by TheGiddyLimit** [comment]
other shit ideas include: add a `.5etools` file to your dir with:

```json
{
  "source": { "json": "a:::::" }
}
```

which would then get read by the tests :^)

**Comment by revilowaldow** [comment]
> `a:::::` and it'd be valid
additionally, if someone had something like `TGLB` - The Giddy Limit Brew
And someone else had `TG:LB` - Top Gaming: Legendary Banter`
Stripping the : out makes them share dirs.

I think I'm in favour of ripping off the band aid of saying no : in brew sources

**Review by revilowaldow — APPROVED** [review]

**Pull request merged**
