### PR TITLE
Adding images

### PR DESCRIPTION
**Pull request by willioz**

### CODE REVIEW

**Review by TheGiddyLimit — APPROVED** [review]

**Comment by revilowaldow** [comment]
First file on this is exactly 25.1Mb right up against the limit. Any reason for it to be that size?

**Review by TheGiddyLimit — CHANGES_REQUESTED** [review]
yeah just checked and the filesize test wasn't enabled 🤦 

have now enabled it, this PR _probably_ doesn't pass

**Comment by willioz** [comment]
Oh I didn't know there was a file limit size, I'll compress the image and resubmit the pr.

**Comment by TheGiddyLimit** [comment]
@willioz since both commits are now in the history, all you've done here is hidden the 25MB version in the logs, where it will forever be clogging up the repo

please do make a new branch and fully re-submit it as a new PR (or if you prefer doing the git `rebase` dance, by all means)

**Pull request closed without merging**
